# Generated by Django 4.0.1 on 2022-01-13 06:50

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='no',
            field=models.CharField(default=main.models.generate_product_id, max_length=10, unique=True),
        ),
    ]
