# Generated by Django 4.0.1 on 2022-01-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review_image_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='video',
            new_name='video_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='default.png', upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Together practice budget deep door physical despite. Over for successful wide foreign speak. Interesting safe street nice. Information success rule south soon.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(default='Catch marriage strong school.'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.CharField(default='Jasmine Perez', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='Enjoy kitchen direction more describe another major.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Douglas Fletcher', max_length=20),
        ),
    ]
