# Generated by Django 4.0.1 on 2022-01-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_video_product_video_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instance',
            new_name='Greeny',
        ),
        migrations.AlterModelOptions(
            name='greeny',
            options={'verbose_name_plural': 'Greeny'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Example return wrong attorney. Yes figure general deep. Red really serious American space once report. Cause get stuff like along. Remain sit wife.', null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(default='Church camera owner contain.'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.CharField(default='Paula Browning', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='Shake bar certain. Crime worry represent rock.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Antonio Lopez', max_length=20),
        ),
    ]
