# Generated by Django 4.0.1 on 2022-01-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_description_alter_reply_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeny',
            name='address',
            field=models.CharField(default='1Hd- 50, 010 Avenue, NY 90001 United States', max_length=200),
        ),
        migrations.AddField(
            model_name='greeny',
            name='facebook',
            field=models.URLField(default='https://facebook.com'),
        ),
        migrations.AddField(
            model_name='greeny',
            name='instagram',
            field=models.URLField(default='https://instagram.com'),
        ),
        migrations.AddField(
            model_name='greeny',
            name='interest',
            field=models.URLField(default='https://pinterest.com'),
        ),
        migrations.AddField(
            model_name='greeny',
            name='linkedin',
            field=models.URLField(default='https://linkedIn.com'),
        ),
        migrations.AddField(
            model_name='greeny',
            name='twitter',
            field=models.URLField(default='https://twitter.com'),
        ),
        migrations.AlterField(
            model_name='greeny',
            name='link',
            field=models.URLField(default='https://elishae.me/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Increase fund raise plan season. Do rock team want by. Positive man accept control society place. Simple dinner return. Total future action official focus final down four. Executive professional service entire.', null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(default='Strategy reach send reveal.'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.CharField(default='Ryan Frazier', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='Catch thus right draw cold sound.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Katherine Lawrence', max_length=20),
        ),
    ]
