# Generated by Django 4.0.1 on 2022-01-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_greeny_address_greeny_facebook_greeny_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='labelClass',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='labelColor',
            field=models.CharField(blank=True, choices=[('new', 'Green'), ('stockout', 'Grey'), ('stockblue', 'Blue'), ('sale', 'Red')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Strategy modern PM. Put reveal wonder environmental condition economy. Likely blue share much thank president when.', null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(default='House middle finally letter painting.'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.CharField(default='Dustin Harris', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='Option identify idea success power up likely student.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Laura Maxwell', max_length=20),
        ),
    ]
