# Generated by Django 4.0.1 on 2022-01-18 02:56

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_rating_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rodney Walton', max_length=20)),
                ('content', models.TextField(default='New small instead defense. Place own machine bill decide then whose. Successful find tree use. Win laugh role feel collection thus.')),
                ('rating', models.IntegerField(default=5, validators=[main.models.validate_rating])),
                ('image', models.ImageField(default='profile.jpg', upload_to='testimonials/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=main.models.generate_discount),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.CharField(default=main.models.generate_old_price, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.IntegerField(default=main.models.generate_order),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Agree must box guess cell then choose. Discover send arrive water. Section order particularly field page approach that. Wish themselves only security chair until turn peace. Seek unit evening wind though have.', null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(default='Yeah score old car.'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.CharField(default='Chase Young', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='Western parent my arm serve. Wall thought leader down case.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Scott Briggs', max_length=20),
        ),
    ]
