# Generated by Django 4.0.1 on 2022-01-18 03:22

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_testimonial_product_discount_product_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Morgan Patterson', max_length=20)),
                ('title', models.CharField(default=main.models.generate_team_title, max_length=50)),
                ('image', models.ImageField(default='profile.jpg', upload_to='team_members/')),
                ('facebook', models.URLField(default='https://facebook.com')),
                ('twitter', models.URLField(default='https://twitter.com')),
                ('linkedin', models.URLField(default='https://linkedIn.com')),
            ],
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(default=main.models.generate_testi_title, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Allow society window sign. Create office agree charge. International speak five see. Bed effort thank theory. Whether role hold campaign.', null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(default='Radio front buy where small action.'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.CharField(default='Ashley Woods', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='Such goal yet step not above. Under letter personal say tell off.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Geoffrey Davis', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(default='Step story major still appear why. Plan magazine behavior sound much usually final. Politics building prevent pattern group for billion still.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='Zachary Greene', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=4, validators=[main.models.validate_rating]),
        ),
    ]
