# Generated by Django 4.0.1 on 2022-01-18 17:42

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_teammember_testimonial_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.png', upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Quite role second instead itself. Raise necessary sign contain or someone. Some yourself person. Left group leader truth history water. Agreement sure something remain station or. Family son without notice yard operation.', null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(default='Speech for five any.'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.CharField(default='Craig Waller', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='Against so interesting now pattern perhaps.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Cheryl Jackson', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(default='Jennifer Williams', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(default='Loss fish right single. Cover contain bank federal.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='Edwin Brown', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5, validators=[main.models.validate_rating]),
        ),
    ]
