# Generated by Django 4.0.1 on 2022-01-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_brand_product_count_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='rating_count',
            field=models.IntegerField(default=42),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Interview professor summer. Think eat miss whether ago actually. Past everybody fill southern say mouth. Rock weight say movement. Remain message voice brother.', null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(default='Race none director.'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.CharField(default='Martin Lane', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='Approach crime because direction everything focus. Money main military will environmental natural much military.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Shelby Lopez', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(default='Lori Ferguson', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(default='Man painting son term bank serious. Consumer boy suggest shoulder face protect name.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='Adam Pruitt', max_length=20),
        ),
    ]
