# Generated by Django 4.0.1 on 2022-01-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_brand_rating_count_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='rating_count',
            field=models.IntegerField(default=38),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Be late whether situation. How various bad amount loss. Which party drug call they see responsibility. Thank away expect out.', null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(default='Young kitchen name.'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.CharField(default='Dalton Hanson', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='Find former project better whose bar computer this. Mean relationship against room.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Angela Perez', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(default='Erik Waters', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(default='After picture where. Music seven pass take ask car.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='Kathleen Smith', max_length=20),
        ),
    ]
