# Generated by Django 4.0.1 on 2022-01-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_brand_rating_count_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='rating_count',
            field=models.IntegerField(default=36),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Phone use kid friend state enough decision. Need him eat tough. Moment production current one direction land. Yeah fear less road since.', null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(default='Health theory source.'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.CharField(default='Jason Herman', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='Control wear detail during capital choice. None despite night around somebody production.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Wanda Collins', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(default='Whitney Mccoy', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(default='Eat interesting interest rate when. All beautiful usually pull every my traditional young.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='Jessica Gonzalez', max_length=20),
        ),
    ]
