# Generated by Django 4.0.1 on 2022-01-18 19:14

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_brand_rating_count_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='rating_count',
            field=models.IntegerField(default=main.models.generate_rating_count),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=main.models.generate_product_description, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(default=main.models.generate_comment_content),
        ),
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.CharField(default=main.models.generate_name, max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default=main.models.generate_comment_content),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default=main.models.generate_name, max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(default=main.models.generate_name, max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(default=main.models.generate_comment_content),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default=main.models.generate_name, max_length=20),
        ),
    ]
