# Generated by Django 4.0.1 on 2022-01-19 08:46

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_product_status_alter_testimonial_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=main.models.generate_testi_rating, validators=[main.models.validate_rating]),
        ),
    ]
