# Generated by Django 4.0.1 on 2022-01-19 12:03

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(default='90 minutes express delivery', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='order',
            name='no',
            field=models.CharField(default=main.models.generate_product_id, max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(default='card payment', max_length=50, null=True),
        ),
    ]
